Queue management in RabbitMQ
Flexberry/NewPlatform.Flexberry.ServiceBus pull request #35
Opened 2018-11-06 07:49 UTC by KollegOFF

2018-11-08 11:03 UTC, bratchikov requested changes

2018-11-08 11:03 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.RabbitMQ/Components/MessageManager/RmqMessageManager.cs
> +        {
Проверка валидности аргументов функции?

2018-11-08 11:03 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.RabbitMQ/Components/MessageManager/RmqMessageManager.cs
> +            IEnumerable<RabbitMQQueue> queues = _managementClient.GetQueuesAsync().Result.Skip(offset).Take(count);
А если что-то пойдёт не так? Как минимум обработать бы Null reference exceptions.

2018-11-08 11:03 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.RabbitMQ/Components/MessageManager/RmqMessageManager.cs
> +        {
Проверить аргумент?

2018-11-08 11:03 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.RabbitMQ/Queue.cs
> +    public class Queue : DataObject
Этот класс сгенерирован? Где скобки программиста?

2018-11-08 11:19 UTC, KollegOFF commented on NewPlatform.Flexberry.ServiceBus.RabbitMQ/Queue.cs
> +    public class Queue : DataObject
Нет.

2018-11-12 09:01 UTC, bratchikov approved these changes

2018-11-12 09:02 UTC, merged