Fix receiving messages with the group
Flexberry/NewPlatform.Flexberry.ServiceBus pull request #36
Opened 2018-11-08 10:25 UTC by KollegOFF

TFS: #171820.

2018-11-08 11:24 UTC, bratchikov requested changes

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.@this)]
Зачем это указано на диаграмме?

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +            // *** Start programmer edit section *** (OnUpdateMessage)
Может проверить статус объекта данных? Код ниже актуален только для Created.

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.IntegratedTests/Components/ReceivingManager/DefaultReceivingManagerTest.cs
> +        public void TestParallelAcceptMessageWithGroup()
XML-комментарий?

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.IntegratedTests/Components/SendingManager/OptimizedSendingManagerTest.cs
> +    public class OptimizedSendingManagerTest : BaseServiceBusIntegratedTest
XML-комментарий?

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.IntegratedTests/Components/SendingManager/OptimizedSendingManagerTest.cs
> +        public void TestDeleteUndeliveredMessageWithGroup()
XML-комментарий?

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                        object @lock;
Не самое удачное название для переменной. Можно чуть подробнее, тогда не придётся использовать @.

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                @lock = new object();
А это вообще законно?
Я не понял этой логики с массивом локов и их пересозданием.

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                var msgWithGroup = new Message { __PrimaryKey = messagesWithGroup[0].__PrimaryKey };
А если их будет 2?

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                _dataService.LoadObject(Message.Views.MessageEditView, msgWithGroup);
Так в коде выше они же вычитаны уже все. Зачем читать ещё раз?

2018-11-08 11:24 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +                DataService.Query<Message>().Count(m =>
Проверь какой SQL генерируется для такой конструкции (не в коде проверь, а так, для себя). Тут явно не указано представление, надо проверить, что SQL генерируется адекватно и сразу на count (проверить, что count не на уровне кода выполняется, а в СУБД).

2018-11-08 11:49 UTC, KollegOFF commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.@this)]
Полномочия не редактируются для бизнес-серверов.

2018-11-08 11:51 UTC, KollegOFF commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +            // *** Start programmer edit section *** (OnUpdateMessage)
Бизнес-сервер навешан только на создание объекта.

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +            // *** Start programmer edit section *** (OnUpdateMessage)
Я бы сказал в будущем это может и поменяться. Лучше проверку все равно добавить, это и намерения проверки лучше прояснит

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +        private readonly Dictionary<Guid, object> locks = new Dictionary<Guid, object>();
Предлагаю ConcurrentDictionary использовать

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +        private readonly Dictionary<Guid, object> locks = new Dictionary<Guid, object>();
Предлагаю в качестве ключа использовать groupName или сочетание ключа подписки и groupName

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +        private readonly object lockForLocks = new object();
С ConcurrentDictionary не понадобится

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                            lcs.LimitFunction = _langDef.GetFunction(
Аналогичный запрос появился в БС-е. Может стоит вынести его в отдельный метод

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                var msgWithGroup = new Message { __PrimaryKey = messagesWithGroup[0].__PrimaryKey };
А их может быть два, если пришел один, начал отправляться, в этот момент пришел второй, начал отправляться, а потом обе отправки зафейлились

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                var msgWithGroup = new Message { __PrimaryKey = messagesWithGroup[0].__PrimaryKey };
А почему тут создаются объекты с фиксированным первичным ключом, а не через SetExistingPrimaryKey? @bratchikov, там же есть разница между этими способами и через SetExisting вроде правильнее?

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                _statisticsService.NotifyAvgTimeSql(subscription, (int)time, "DefaultReceivingManager.AcceptMessage(MessageForESB message, string groupName) load group messages.");
{nameof(DefauleReceivingManager)}.{nameof(AcceptMessage)}({nameof(MessageForESB) {nameof(message)}, string {nameof(groupName)})

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                _statisticsService.NotifyAvgTimeSql(subscription, (int)time, "DefaultReceivingManager.AcceptMessage(MessageForESB message, string groupName) update group messages.");
аналогично про nameof

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                        locks.Remove(guid);
Сразу удалять лок нельзя. Может произойти так, что первый поток создал в словаре блокировку, затем второй поток ее из словаря достал и на нее залочился, потом первый поток завершился и из словаря блокировку удалил, второй поток зашел в критическую секцию, а в этот момент третий поток создал уже новую блокировку по этому же ключу, и вот у тебя два потока параллельно одно сообщение колбасят.

Предлагаю в локе хранить время последнего обращения и в фоновом потоке чистить словарь локов, удаляя давно не использовавшиеся локи. Это все равно не 100% гарантия, но гораздо реже будут баги случаться. Ну и сделать это поведение отключаемым (например через таймаут протухания = 0, чтобы те, кому не страшно память локами забить, вообще с такой ошибкой не сталкивались)

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                ServiceHelper.SetMessageWithGroupValues(message, subscription, msgWithGroup, groupName, _dataService, _logger, _statisticsService);
Вроде разница между if и else только в одной строке - создании объекта message. Предлагаю общую часть после if вынести

2018-11-09 09:02 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/SendingManager/OptimizedSendingManager.cs
> +                    m.__PrimaryKey != message.__PrimaryKey &&
Опять то же ограничение

2018-11-12 07:25 UTC, KollegOFF commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                                _dataService.LoadObject(Message.Views.MessageEditView, msgWithGroup);
Разные представления.

2018-11-12 07:28 UTC, KollegOFF commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +                DataService.Query<Message>().Count(m =>
Представление верное, SQL без count'а, но в `LoadingCustomizationStruct` у `ReturnType` значение `Count`.

2018-11-12 09:14 UTC, bratchikov requested changes

2018-11-12 09:14 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +                DataService.Query<Message>().Count(m =>
Давай перепишем на LCS? Чтобы count был прямо в SQL (надо вызвать не LoadObject, а GetObjectsCount(lcs))

2018-11-12 09:14 UTC, bratchikov commented on NewPlatform.Flexberry.ServiceBus/Utils/KeyLocker.cs
> +                Lock @lock;
Не самое удачное имя переменной.

2018-11-12 09:52 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus.BusinessServers/BusinessServers/MessageBS.cs
> +                DataService.Query<Message>().Count(m =>
А формирование LimitFunction в отдельный метод БС-а, чтобы в других местах тоже его использовать

2018-11-12 09:52 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Components/ReceivingManager/DefaultReceivingManager.cs
> +                        locker.FreeLock(lockKey);
Если исключение будет в методе GetLock, то счетчик не увеличится, а здесь ты его уменьшишь и чей-то чужой лок освободишь

2018-11-12 09:52 UTC, mao29 commented on NewPlatform.Flexberry.ServiceBus/Utils/KeyLocker.cs
> +        private Dictionary<T1, Lock> locks = new Dictionary<T1, Lock>();
Лучше использовать ConcurrentDictionary. Для случая, когда часто создаются записи по новым ключам и реже изменяются записи по уже существующим, он будет выигрывать у глобальной блокировки доступа к обычному словарю. Вот обсуждение в тему https://stackoverflow.com/questions/1949131/net-dictionary-locking-vs-concurrentdictionary, там все комменты стоят внимания. Надо только использовать методы GetOrAdd и AddOrUpdate для работы, а не TryGetValue

2018-11-13 09:37 UTC, bratchikov approved these changes

2018-11-13 09:43 UTC, merged