Moq callback with ref
Flexberry/NewPlatform.Flexberry.ServiceBus pull request #98
Opened 2021-09-02 11:54 UTC by VChurekov

2021-09-02 12:01 UTC, NicholasNoise commented
change the base branch to develop-v2.0

2021-09-02 12:17 UTC, NicholasNoise requested changes

2021-09-02 12:17 UTC, NicholasNoise commented on NewPlatform.Flexberry.ServiceBus/Components/ObjectRepository/CachedDataServiceObjectRepository.cs
> +                    if (data != null)
А для mssql нужен такой фикс?

2021-09-07 12:27 UTC, VChurekov commented on NewPlatform.Flexberry.ServiceBus/Components/ObjectRepository/CachedDataServiceObjectRepository.cs
> +                    if (data != null)
Да, нужен. Добавил фикс.

2021-09-08 06:17 UTC, NicholasNoise approved these changes

2021-09-08 07:25 UTC, bratchikov approved these changes

2021-09-13 15:29 UTC, merged